"""Money/points ledger for a Jev Poker match, and its captured output files.

Chips double as dollars for the demo: each chip is $1. We track both the money
(net chips won) and points (hands won) for each player so a finished match can be
rendered as a scoreboard and committed or uploaded as a CI artifact.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path


@dataclass
class HandRecord:
    hand: int
    winner: str
    pot: int
    money_a: int  # net chips won/lost by player A this hand
    money_b: int


@dataclass
class Scoreboard:
    name_a: str = "Jev"
    name_b: str = "HouseBot"
    starting_money: int = 200
    hands: list[HandRecord] = field(default_factory=list)

    def record(self, hand: int, winner: str, pot: int, money_a: int, money_b: int) -> None:
        self.hands.append(HandRecord(hand, winner, pot, money_a, money_b))

    @property
    def money_a(self) -> int:
        return self.starting_money + sum(row.money_a for row in self.hands)

    @property
    def money_b(self) -> int:
        return self.starting_money + sum(row.money_b for row in self.hands)

    @property
    def points_a(self) -> int:
        return sum(1 for row in self.hands if row.money_a > 0)

    @property
    def points_b(self) -> int:
        return sum(1 for row in self.hands if row.money_b > 0)

    @property
    def splits(self) -> int:
        return sum(1 for row in self.hands if row.money_a == 0 and row.money_b == 0)

    def to_dict(self) -> dict:
        return {
            "players": {self.name_a: "A", self.name_b: "B"},
            "starting_money": self.starting_money,
            "hands_played": len(self.hands),
            "points": {self.name_a: self.points_a, self.name_b: self.points_b, "splits": self.splits},
            "money": {self.name_a: self.money_a, self.name_b: self.money_b},
            "net": {self.name_a: self.money_a - self.starting_money, self.name_b: self.money_b - self.starting_money},
            "ledger": [asdict(row) for row in self.hands],
        }

    def to_markdown(self) -> str:
        net_a = self.money_a - self.starting_money
        net_b = self.money_b - self.starting_money
        leader = self.name_a if net_a > net_b else (self.name_b if net_b > net_a else "tie")
        lines = [
            "# Scoreboard",
            "",
            f"Money and points between **{self.name_a}** and **{self.name_b}**.",
            "Chips double as dollars ($1 per chip). Generated by `jev-poker`.",
            "",
            "| Player | Money | Net | Hands won |",
            "| --- | ---: | ---: | ---: |",
            f"| {self.name_a} | ${self.money_a} | {net_a:+d} | {self.points_a} |",
            f"| {self.name_b} | ${self.money_b} | {net_b:+d} | {self.points_b} |",
            "",
            f"Hands played: **{len(self.hands)}** · splits: **{self.splits}** · leader: **{leader}**",
            "",
        ]
        if self.hands:
            lines += [
                "## Hand ledger",
                "",
                "| Hand | Winner | Pot | Net A | Net B |",
                "| ---: | --- | ---: | ---: | ---: |",
            ]
            for row in self.hands:
                lines.append(f"| {row.hand} | {row.winner} | {row.pot} | {row.money_a:+d} | {row.money_b:+d} |")
            lines.append("")
        return "\n".join(lines)

    def write(self, directory: str | Path) -> tuple[Path, Path]:
        target = Path(directory)
        target.mkdir(parents=True, exist_ok=True)
        json_path = target / "scoreboard.json"
        md_path = target / "SCOREBOARD.md"
        json_path.write_text(json.dumps(self.to_dict(), indent=2) + "\n")
        md_path.write_text(self.to_markdown())
        return json_path, md_path
